# Databricks notebook source
# MAGIC %md
# MAGIC # LoRa — Bronze Ingestion (one-time)
# MAGIC
# MAGIC Reads the two source files from a Unity Catalog Volume and lands them as Delta tables
# MAGIC that the **Lakeflow Designer pipeline** (`01_dlt_lakeflow_pipeline`) will consume.
# MAGIC
# MAGIC | Source file | Target Delta table |
# MAGIC |---|---|
# MAGIC | `site_lat_long.csv` | `{catalog}.{schema}.sites_bronze` |
# MAGIC | `Top100_SmallRural_County_Markets_2021.TAB` (+ DAT/MAP/ID/IND) | `{catalog}.{schema}.county_markets_bronze` |
# MAGIC
# MAGIC ### How to use
# MAGIC
# MAGIC 1. Set the three widgets at the top (catalog / schema / volume_path).
# MAGIC 2. Attach to **Serverless** (or any cluster — install cell handles both).
# MAGIC 3. Run All.
# MAGIC
# MAGIC Run this notebook **once** to seed the bronze layer, or whenever the source files refresh.
# MAGIC Everything downstream lives in the Lakeflow Designer pipeline and runs on its own schedule.
# MAGIC
# MAGIC **Why a notebook (not Designer) for this step?** MapInfo `.TAB` is a proprietary GIS
# MAGIC format with 5 sidecar files. Designer's built-in connectors don't read it; `geopandas`
# MAGIC (GDAL under the hood) handles it transparently. After this notebook runs once, every
# MAGIC future step is fully visual in Designer.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Parameters

# COMMAND ----------

dbutils.widgets.text("catalog",     "cmegdemos_catalog",                "1. Catalog")
dbutils.widgets.text("schema",      "network_analytics_enablement",     "2. Schema")
dbutils.widgets.text("volume_path", "/Volumes/cmegdemos_catalog/network_analytics_enablement/lora", "3. Volume path (with raw files)")

CATALOG     = dbutils.widgets.get("catalog")
SCHEMA      = dbutils.widgets.get("schema")
VOLUME_PATH = dbutils.widgets.get("volume_path")

print(f"Catalog:     {CATALOG}")
print(f"Schema:      {SCHEMA}")
print(f"Volume path: {VOLUME_PATH}")

# COMMAND ----------

# MAGIC %pip install geopandas pyogrio --quiet
# MAGIC %restart_python

# COMMAND ----------

# Re-read widgets after %restart_python (Python state is cleared)
CATALOG     = dbutils.widgets.get("catalog")
SCHEMA      = dbutils.widgets.get("schema")
VOLUME_PATH = dbutils.widgets.get("volume_path")

spark.sql(f"USE CATALOG {CATALOG}")
spark.sql(f"USE SCHEMA {SCHEMA}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sites CSV → `sites_bronze`

# COMMAND ----------

sites_df = (
    spark.read
        .option("header", "true")
        .option("inferSchema", "true")
        .csv(f"{VOLUME_PATH}/site_lat_long.csv")
)

(sites_df.write
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable("sites_bronze"))

print(f"sites_bronze: {spark.table('sites_bronze').count():,} rows")
display(spark.table("sites_bronze").limit(5))

# COMMAND ----------

# MAGIC %md
# MAGIC ## MapInfo TAB polygons → `county_markets_bronze`
# MAGIC
# MAGIC `geopandas.read_file` opens the `.TAB` (and the DAT/MAP/ID/IND sidecars) transparently.
# MAGIC Polygons are reprojected to WGS84 and simplified to ~100 m tolerance — fine for
# MAGIC "is this site inside this market" determination and keeps each row under Spark's
# MAGIC per-row buffer limit.

# COMMAND ----------

import geopandas as gpd
from pyspark.sql.types import StructType, StructField, StringType, IntegerType

gdf = gpd.read_file(f"{VOLUME_PATH}/Top100_SmallRural_County_Markets_2021.TAB")
print(f"Polygons read: {len(gdf):,}  |  source CRS: {gdf.crs}")

gdf_wgs84 = gdf.to_crs(epsg=4326)
gdf_wgs84["geometry"] = gdf_wgs84["geometry"].simplify(tolerance=0.001, preserve_topology=True)
gdf_wgs84["geometry_wkt"] = gdf_wgs84["geometry"].apply(lambda g: g.wkt if g is not None else None)
print(f"Max WKT length after simplify: {gdf_wgs84['geometry_wkt'].str.len().max():,} chars")

schema = StructType([
    StructField("ID", StringType(), True),
    StructField("Name", StringType(), True),
    StructField("State", StringType(), True),
    StructField("MarketType", StringType(), True),
    StructField("MarketTypeDetailed", StringType(), True),
    StructField("Population", IntegerType(), True),
    StructField("geometry_wkt", StringType(), True),
])

pdf = gdf_wgs84.drop(columns=["geometry"])
markets_df = spark.createDataFrame(pdf[[f.name for f in schema.fields]], schema=schema)

(markets_df.repartition(16).write
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable("county_markets_bronze"))

print(f"county_markets_bronze: {spark.table('county_markets_bronze').count():,} rows")
display(spark.table("county_markets_bronze").limit(5))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Bronze layer ready
# MAGIC
# MAGIC ### Tables generated by this notebook
# MAGIC
# MAGIC | Table | Source file | Expected rows (demo data) |
# MAGIC |---|---|---:|
# MAGIC | `{catalog}.{schema}.sites_bronze` | `site_lat_long.csv` | 1,000 |
# MAGIC | `{catalog}.{schema}.county_markets_bronze` | `Top100_SmallRural_County_Markets_2021.TAB` (+ DAT/MAP/ID/IND) | 2,179 |
# MAGIC
# MAGIC Everything downstream (`sites_silver`, `markets_silver`, `sites_in_market`, `sites_nearest_market`, `site_market_enriched`) is produced by the **Lakeflow Designer pipeline** (`01_dlt_lakeflow_pipeline`) — not this notebook.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Quick verification: list the bronze tables and their row counts
# MAGIC SELECT 'sites_bronze'          AS table_name, COUNT(*) AS rows FROM sites_bronze
# MAGIC UNION ALL
# MAGIC SELECT 'county_markets_bronze' AS table_name, COUNT(*) AS rows FROM county_markets_bronze;
